// 聖經書卷數據初始化
export interface BibleBookData {
  name: string;
  englishName: string;
  testament: "OLD" | "NEW";
  order: number;
  chapters: number;
  description: string;
  color: string;
}

export const bibleBooks: BibleBookData[] = [
  // 舊約 39卷
  {
    name: "創世記",
    englishName: "Genesis",
    testament: "OLD",
    order: 1,
    chapters: 50,
    description: "神創造天地萬物和人類始祖",
    color: "#8B4513",
  },
  {
    name: "出埃及記",
    englishName: "Exodus",
    testament: "OLD",
    order: 2,
    chapters: 40,
    description: "以色列人出埃及，神頒布律法",
    color: "#8B4513",
  },
  {
    name: "利未記",
    englishName: "Leviticus",
    testament: "OLD",
    order: 3,
    chapters: 27,
    description: "祭司制度和獻祭條例",
    color: "#8B4513",
  },
  {
    name: "民數記",
    englishName: "Numbers",
    testament: "OLD",
    order: 4,
    chapters: 36,
    description: "以色列人在曠野的旅程",
    color: "#8B4513",
  },
  {
    name: "申命記",
    englishName: "Deuteronomy",
    testament: "OLD",
    order: 5,
    chapters: 34,
    description: "摩西臨終前的勸勉",
    color: "#8B4513",
  },
  {
    name: "約書亞記",
    englishName: "Joshua",
    testament: "OLD",
    order: 6,
    chapters: 24,
    description: "約書亞帶領以色列人進入迦南",
    color: "#8B4513",
  },
  {
    name: "士師記",
    englishName: "Judges",
    testament: "OLD",
    order: 7,
    chapters: 21,
    description: "士師時代的歷史",
    color: "#8B4513",
  },
  {
    name: "路得記",
    englishName: "Ruth",
    testament: "OLD",
    order: 8,
    chapters: 4,
    description: "路得的故事，大衛王的祖先",
    color: "#8B4513",
  },
  {
    name: "撒母耳記上",
    englishName: "1 Samuel",
    testament: "OLD",
    order: 9,
    chapters: 31,
    description: "撒母耳和掃羅王的故事",
    color: "#8B4513",
  },
  {
    name: "撒母耳記下",
    englishName: "2 Samuel",
    testament: "OLD",
    order: 10,
    chapters: 24,
    description: "大衛王統治時期",
    color: "#8B4513",
  },
  {
    name: "列王紀上",
    englishName: "1 Kings",
    testament: "OLD",
    order: 11,
    chapters: 22,
    description: "所羅門王和分裂王國",
    color: "#8B4513",
  },
  {
    name: "列王紀下",
    englishName: "2 Kings",
    testament: "OLD",
    order: 12,
    chapters: 25,
    description: "南北王國的滅亡",
    color: "#8B4513",
  },
  {
    name: "歷代志上",
    englishName: "1 Chronicles",
    testament: "OLD",
    order: 13,
    chapters: 29,
    description: "大衛王朝的家譜和歷史",
    color: "#8B4513",
  },
  {
    name: "歷代志下",
    englishName: "2 Chronicles",
    testament: "OLD",
    order: 14,
    chapters: 36,
    description: "猶大王國的歷史",
    color: "#8B4513",
  },
  {
    name: "以斯拉記",
    englishName: "Ezra",
    testament: "OLD",
    order: 15,
    chapters: 10,
    description: "被擄歸回重建聖殿",
    color: "#8B4513",
  },
  {
    name: "尼希米記",
    englishName: "Nehemiah",
    testament: "OLD",
    order: 16,
    chapters: 13,
    description: "重建耶路撒冷城牆",
    color: "#8B4513",
  },
  {
    name: "以斯帖記",
    englishName: "Esther",
    testament: "OLD",
    order: 17,
    chapters: 10,
    description: "以斯帖拯救猶太人",
    color: "#8B4513",
  },
  {
    name: "約伯記",
    englishName: "Job",
    testament: "OLD",
    order: 18,
    chapters: 42,
    description: "約伯的苦難和信心",
    color: "#FFD700",
  },
  {
    name: "詩篇",
    englishName: "Psalms",
    testament: "OLD",
    order: 19,
    chapters: 150,
    description: "大衛和眾人的詩歌",
    color: "#FFD700",
  },
  {
    name: "箴言",
    englishName: "Proverbs",
    testament: "OLD",
    order: 20,
    chapters: 31,
    description: "所羅門的智慧箴言",
    color: "#FFD700",
  },
  {
    name: "傳道書",
    englishName: "Ecclesiastes",
    testament: "OLD",
    order: 21,
    chapters: 12,
    description: "所羅門的人生感悟",
    color: "#FFD700",
  },
  {
    name: "雅歌",
    englishName: "Song of Songs",
    testament: "OLD",
    order: 22,
    chapters: 8,
    description: "所羅門的愛情詩歌",
    color: "#FFD700",
  },
  {
    name: "以賽亞書",
    englishName: "Isaiah",
    testament: "OLD",
    order: 23,
    chapters: 66,
    description: "以賽亞先知的預言",
    color: "#DC143C",
  },
  {
    name: "耶利米書",
    englishName: "Jeremiah",
    testament: "OLD",
    order: 24,
    chapters: 52,
    description: "耶利米先知的預言",
    color: "#DC143C",
  },
  {
    name: "耶利米哀歌",
    englishName: "Lamentations",
    testament: "OLD",
    order: 25,
    chapters: 5,
    description: "耶利米為耶路撒冷哀哭",
    color: "#DC143C",
  },
  {
    name: "以西結書",
    englishName: "Ezekiel",
    testament: "OLD",
    order: 26,
    chapters: 48,
    description: "以西結先知的異象",
    color: "#DC143C",
  },
  {
    name: "但以理書",
    englishName: "Daniel",
    testament: "OLD",
    order: 27,
    chapters: 12,
    description: "但以理在巴比倫的經歷",
    color: "#DC143C",
  },
  {
    name: "何西阿書",
    englishName: "Hosea",
    testament: "OLD",
    order: 28,
    chapters: 14,
    description: "何西阿先知的婚姻比喻",
    color: "#DC143C",
  },
  {
    name: "約珥書",
    englishName: "Joel",
    testament: "OLD",
    order: 29,
    chapters: 3,
    description: "約珥先知的預言",
    color: "#DC143C",
  },
  {
    name: "阿摩司書",
    englishName: "Amos",
    testament: "OLD",
    order: 30,
    chapters: 9,
    description: "阿摩司先知的社會公義",
    color: "#DC143C",
  },
  {
    name: "俄巴底亞書",
    englishName: "Obadiah",
    testament: "OLD",
    order: 31,
    chapters: 1,
    description: "俄巴底亞對以東的預言",
    color: "#DC143C",
  },
  {
    name: "約拿書",
    englishName: "Jonah",
    testament: "OLD",
    order: 32,
    chapters: 4,
    description: "約拿先知和尼尼微城",
    color: "#DC143C",
  },
  {
    name: "彌迦書",
    englishName: "Micah",
    testament: "OLD",
    order: 33,
    chapters: 7,
    description: "彌迦先知的預言",
    color: "#DC143C",
  },
  {
    name: "那鴻書",
    englishName: "Nahum",
    testament: "OLD",
    order: 34,
    chapters: 3,
    description: "那鴻對尼尼微的預言",
    color: "#DC143C",
  },
  {
    name: "哈巴谷書",
    englishName: "Habakkuk",
    testament: "OLD",
    order: 35,
    chapters: 3,
    description: "哈巴谷先知的疑問",
    color: "#DC143C",
  },
  {
    name: "西番雅書",
    englishName: "Zephaniah",
    testament: "OLD",
    order: 36,
    chapters: 3,
    description: "西番雅先知的預言",
    color: "#DC143C",
  },
  {
    name: "哈該書",
    englishName: "Haggai",
    testament: "OLD",
    order: 37,
    chapters: 2,
    description: "哈該先知鼓勵建殿",
    color: "#DC143C",
  },
  {
    name: "撒迦利亞書",
    englishName: "Zechariah",
    testament: "OLD",
    order: 38,
    chapters: 14,
    description: "撒迦利亞先知的異象",
    color: "#DC143C",
  },
  {
    name: "瑪拉基書",
    englishName: "Malachi",
    testament: "OLD",
    order: 39,
    chapters: 4,
    description: "瑪拉基先知的最後預言",
    color: "#DC143C",
  },

  // 新約 27卷
  {
    name: "馬太福音",
    englishName: "Matthew",
    testament: "NEW",
    order: 40,
    chapters: 28,
    description: "耶穌基督的家譜和事工",
    color: "#32CD32",
  },
  {
    name: "馬可福音",
    englishName: "Mark",
    testament: "NEW",
    order: 41,
    chapters: 16,
    description: "耶穌基督的僕人事工",
    color: "#32CD32",
  },
  {
    name: "路加福音",
    englishName: "Luke",
    testament: "NEW",
    order: 42,
    chapters: 24,
    description: "路加醫生記錄的耶穌生平",
    color: "#32CD32",
  },
  {
    name: "約翰福音",
    englishName: "John",
    testament: "NEW",
    order: 43,
    chapters: 21,
    description: "約翰使徒見證耶穌是神",
    color: "#32CD32",
  },
  {
    name: "使徒行傳",
    englishName: "Acts",
    testament: "NEW",
    order: 44,
    chapters: 28,
    description: "初期教會的建立和發展",
    color: "#4169E1",
  },
  {
    name: "羅馬書",
    englishName: "Romans",
    testament: "NEW",
    order: 45,
    chapters: 16,
    description: "保羅闡述因信稱義的真理",
    color: "#4169E1",
  },
  {
    name: "哥林多前書",
    englishName: "1 Corinthians",
    testament: "NEW",
    order: 46,
    chapters: 16,
    description: "保羅對哥林多教會的教導",
    color: "#4169E1",
  },
  {
    name: "哥林多後書",
    englishName: "2 Corinthians",
    testament: "NEW",
    order: 47,
    chapters: 13,
    description: "保羅的使徒職分和勸勉",
    color: "#4169E1",
  },
  {
    name: "加拉太書",
    englishName: "Galatians",
    testament: "NEW",
    order: 48,
    chapters: 6,
    description: "保羅捍衛因信稱義的真理",
    color: "#4169E1",
  },
  {
    name: "以弗所書",
    englishName: "Ephesians",
    testament: "NEW",
    order: 49,
    chapters: 6,
    description: "保羅論教會的奧秘",
    color: "#4169E1",
  },
  {
    name: "腓立比書",
    englishName: "Philippians",
    testament: "NEW",
    order: 50,
    chapters: 4,
    description: "保羅在獄中的喜樂",
    color: "#4169E1",
  },
  {
    name: "歌羅西書",
    englishName: "Colossians",
    testament: "NEW",
    order: 51,
    chapters: 4,
    description: "保羅論基督的超越性",
    color: "#4169E1",
  },
  {
    name: "帖撒羅尼迦前書",
    englishName: "1 Thessalonians",
    testament: "NEW",
    order: 52,
    chapters: 5,
    description: "保羅論主再來的盼望",
    color: "#4169E1",
  },
  {
    name: "帖撒羅尼迦後書",
    englishName: "2 Thessalonians",
    testament: "NEW",
    order: 53,
    chapters: 3,
    description: "保羅論主再來的時間",
    color: "#4169E1",
  },
  {
    name: "提摩太前書",
    englishName: "1 Timothy",
    testament: "NEW",
    order: 54,
    chapters: 6,
    description: "保羅對提摩太的牧養指導",
    color: "#4169E1",
  },
  {
    name: "提摩太後書",
    englishName: "2 Timothy",
    testament: "NEW",
    order: 55,
    chapters: 4,
    description: "保羅臨終前的囑咐",
    color: "#4169E1",
  },
  {
    name: "提多書",
    englishName: "Titus",
    testament: "NEW",
    order: 56,
    chapters: 3,
    description: "保羅對提多的教導",
    color: "#4169E1",
  },
  {
    name: "腓利門書",
    englishName: "Philemon",
    testament: "NEW",
    order: 57,
    chapters: 1,
    description: "保羅為阿尼西母求情",
    color: "#4169E1",
  },
  {
    name: "希伯來書",
    englishName: "Hebrews",
    testament: "NEW",
    order: 58,
    chapters: 13,
    description: "基督超越舊約的獻祭",
    color: "#4169E1",
  },
  {
    name: "雅各書",
    englishName: "James",
    testament: "NEW",
    order: 59,
    chapters: 5,
    description: "雅各論信心與行為",
    color: "#4169E1",
  },
  {
    name: "彼得前書",
    englishName: "1 Peter",
    testament: "NEW",
    order: 60,
    chapters: 5,
    description: "彼得論基督徒的盼望",
    color: "#4169E1",
  },
  {
    name: "彼得後書",
    englishName: "2 Peter",
    testament: "NEW",
    order: 61,
    chapters: 3,
    description: "彼得論假教師的警告",
    color: "#4169E1",
  },
  {
    name: "約翰一書",
    englishName: "1 John",
    testament: "NEW",
    order: 62,
    chapters: 5,
    description: "約翰論愛神和愛人",
    color: "#4169E1",
  },
  {
    name: "約翰二書",
    englishName: "2 John",
    testament: "NEW",
    order: 63,
    chapters: 1,
    description: "約翰論愛與真理",
    color: "#4169E1",
  },
  {
    name: "約翰三書",
    englishName: "3 John",
    testament: "NEW",
    order: 64,
    chapters: 1,
    description: "約翰論接待客旅",
    color: "#4169E1",
  },
  {
    name: "猶大書",
    englishName: "Jude",
    testament: "NEW",
    order: 65,
    chapters: 1,
    description: "猶大論假教師的警告",
    color: "#4169E1",
  },
  {
    name: "啟示錄",
    englishName: "Revelation",
    testament: "NEW",
    order: 66,
    chapters: 22,
    description: "約翰看見的末世異象",
    color: "#DC143C",
  },
];

// 預設分類數據
export const defaultCategories = [
  {
    name: "救贖論",
    slug: "soteriology",
    description: "關於救恩的教義",
    color: "#FF6B6B",
    icon: "🕊️",
    order: 1,
  },
  {
    name: "教會論",
    slug: "ecclesiology",
    description: "關於教會的教義",
    color: "#4ECDC4",
    icon: "⛪",
    order: 2,
  },
  {
    name: "末世論",
    slug: "eschatology",
    description: "關於末世的教義",
    color: "#45B7D1",
    icon: "🌅",
    order: 3,
  },
  {
    name: "基督論",
    slug: "christology",
    description: "關於基督的教義",
    color: "#96CEB4",
    icon: "✝️",
    order: 4,
  },
  {
    name: "聖靈論",
    slug: "pneumatology",
    description: "關於聖靈的教義",
    color: "#FFEAA7",
    icon: "🕊️",
    order: 5,
  },
  {
    name: "神論",
    slug: "theology",
    description: "關於神的教義",
    color: "#DDA0DD",
    icon: "👑",
    order: 6,
  },
  {
    name: "人論",
    slug: "anthropology",
    description: "關於人的教義",
    color: "#98D8C8",
    icon: "👤",
    order: 7,
  },
  {
    name: "聖經論",
    slug: "bibliology",
    description: "關於聖經的教義",
    color: "#F7DC6F",
    icon: "📖",
    order: 8,
  },
];

// 預設標籤數據
export const defaultTags = [
  {
    name: "登山寶訓",
    slug: "sermon-on-mount",
    description: "馬太福音5-7章",
    color: "#FF9A76",
    count: 0,
  },
  {
    name: "十誡",
    slug: "ten-commandments",
    description: "出埃及記20章",
    color: "#FF6B6B",
    count: 0,
  },
  {
    name: "愛",
    slug: "love",
    description: "愛的教導",
    color: "#FF69B4",
    count: 0,
  },
  {
    name: "信心",
    slug: "faith",
    description: "信心的教導",
    color: "#32CD32",
    count: 0,
  },
  {
    name: "盼望",
    slug: "hope",
    description: "盼望的教導",
    color: "#4169E1",
    count: 0,
  },
  {
    name: "恩典",
    slug: "grace",
    description: "神的恩典",
    color: "#9370DB",
    count: 0,
  },
  {
    name: "禱告",
    slug: "prayer",
    description: "禱告的教導",
    color: "#20B2AA",
    count: 0,
  },
  {
    name: "敬拜",
    slug: "worship",
    description: "敬拜的教導",
    color: "#FFD700",
    count: 0,
  },
];
